apiVersion: v1
kind: Pod
metadata:
  name: applicationpod
spec:
  conatiner:
  - name: applicationcontainers
    image: bash
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: password
    command: ["echo"]
    args: [$(DB_USER) $(DB_PASS)]
