apiVersion: v1
kind: Pod
metadata:
  name: applicationpod
spec:
  containers:
  - name: applicationcontainers
    image: nginx
    volumeMounts:
    - name: secretvolume
      path: "opt/secret"
  volume:
  - name: secretvolume
    secret:
      secretName: dbsecret
      defaultMode: 256
